Update jsontoyaml

diff --git a/jsontoyaml b/jsontoyaml
--- a/jsontoyaml
+++ b/jsontoyaml
@@ -1,1 +1,27 @@
 #
+trigger:
+- master
+
+pool:
+  vmImage: 'ubuntu-latest'
+
+steps:
+- script: |
+    expirationDates=$(cat white.yaml | jq -r '.vulnerabilities | to_entries[].value[].expirationDate')
+
+    for expirationDate in $expirationDates; do
+      expirationDateEpoch=$(date -d "$expirationDate" +%s)
+      currentDateEpoch=$(date +%s)
+      
+      # Calculate the difference in seconds
+      differenceInSeconds=$((expirationDateEpoch - currentDateEpoch))
+      
+      # Check if the difference is less than 7 days (604800 seconds)
+      if [ $differenceInSeconds -lt 604800 ]; then
+        echo "Error: Expiration date $expirationDate is less than 7 days from today."
+        exit 1
+      fi
+    done
+
+  displayName: 'Check Expiration Dates'
+
